// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTpQ24v1oCxMg2SEdw5HO7HXUzUbTcEhU',
    appId: '1:440453449180:web:0688501afcee945f333b19',
    messagingSenderId: '440453449180',
    projectId: 'track-my-vol',
    authDomain: 'track-my-vol.firebaseapp.com',
    storageBucket: 'track-my-vol.appspot.com',
    measurementId: 'G-4D6X11XDQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOZxs7ArNqgGi_xPs4gWvtu3gXkKP-0Vo',
    appId: '1:440453449180:android:6cbfd049bb3984ea333b19',
    messagingSenderId: '440453449180',
    projectId: 'track-my-vol',
    storageBucket: 'track-my-vol.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgaXfnzkgQpDVc_kQgakK18zSITW_PYME',
    appId: '1:440453449180:ios:515eff27e9b2c094333b19',
    messagingSenderId: '440453449180',
    projectId: 'track-my-vol',
    storageBucket: 'track-my-vol.appspot.com',
    iosClientId:
        '440453449180-j8j5vtdsakth36i11i94sc1ncgal4s3p.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackMyVol2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgaXfnzkgQpDVc_kQgakK18zSITW_PYME',
    appId: '1:440453449180:ios:e08f2caadcc50222333b19',
    messagingSenderId: '440453449180',
    projectId: 'track-my-vol',
    storageBucket: 'track-my-vol.appspot.com',
    iosClientId:
        '440453449180-gm2303ni713aiem5hon6d1re4qrripnm.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackMyVol2.RunnerTests',
  );
}
